In [6]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import skbio
from skbio.metadata import SampleMetadata

skbio.__version__

'0.7.1.post1'

In [2]:
!ls ../../data

emp500  il6.ffn

In [3]:
DATA = '../../data/emp500'

In [4]:
!ls $DATA

amplicon   assembly   masspec    README.md  sample.tsv shotgun

In [5]:
!head $DATA/README.md

# The EMP500 Dataset

The Earth Microbiome Project 500 (EMP500) was a multi-omic study of microbial
communities sampled from various biomes and habitats of the planet. The study
was published in:

- Shaffer, J. P., Nothias, L. F., Thompson, L. R., Sanders, J. G., Salido, R.
  A., Couvillion, S. P., ... & Knight, R. (2022). Standardized multi-omics of
  Earth’s microbiomes reveals microbial and metabolite diversity. Nature
  Microbiology, 7(12), 2128-2150.

### Sample metadata

In [8]:
meta = pd.read_csv(f'{DATA}/sample.tsv', sep='\t', index_col=0)
meta.head()

,sample_name_original,sample_type,collection_timestamp,country,depth_sample,description,elevation,emp500_principal_investigator,emp500_study_id,emp500_pi_study_id,...,env_feature,env_material,env_package,geo_loc_name,host_subject_id,host_scientific_name,latitude,longitude,project_name,scientific_name
sample_name,,,,,,,,,,,,,,,,,,,,,
13114.angenent.65.s001,Angenent65.misc.104,bioreactor sludge,08/09/2011 0:00,USA - New York,not applicable,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.104,not applicable,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome
13114.angenent.65.s002,Angenent65.misc.519,bioreactor sludge,9/27/12 0:00,USA - New York,not applicable,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.519,not applicable,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome
13114.angenent.65.s003,Angenent65.misc.946,bioreactor sludge,11/28/13 0:00,USA - New York,not applicable,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.104,not applicable,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome
13114.angenent.65.s004,Angenent65.misc.1022,bioreactor sludge,02/12/2014 0:00,USA - New York,not applicable,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.519,not applicable,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome
13114.angenent.65.s005,Angenent65.misc.1538,bioreactor sludge,7/13/15 0:00,USA - New York,not applicable,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.1538,not applicable,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome

In [9]:
meta = SampleMetadata.load(
    f'{DATA}/sample.tsv', default_missing_scheme='INSDC:missing')
print(type(meta))
meta

<class 'skbio.metadata._metadata.SampleMetadata'>

SampleMetadata
--------------
880 IDs x 33 columns
sample_name_original:          ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
sample_type:                   ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
collection_timestamp:          ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
country:                       ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
depth_sample:                  ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
description:                   ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
elevation:                     ColumnProperties(type='numeric', missing_scheme='INSDC:missing')
emp500_principal_investigator: ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
emp500_study_id:               ColumnProperties(type='numeric', missing_scheme='INSDC:missing')
emp500_pi_study_id:            ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
emp500_title:                  ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_0:                        ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_1:                        ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_2:                        ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_3:                        ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_salinity:                 ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_v2_2:                     ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_v2_3a:                    ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_v2_3b:                    ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_v2_4a:                    ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_v2_4b:                    ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
empo_4:                        ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
env_biome:                     ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
env_feature:                   ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
env_material:                  ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
env_package:                   ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
geo_loc_name:                  ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
host_subject_id:               ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
host_scientific_name:          ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
latitude:                      ColumnProperties(type='numeric', missing_scheme='INSDC:missing')
longitude:                     ColumnProperties(type='numeric', missing_scheme='INSDC:missing')
project_name:                  ColumnProperties(type='categorical', missing_scheme='INSDC:missing')
scientific_name:               ColumnProperties(type='categorical', missing_scheme='INSDC:missing')

Call to_dataframe() for a tabular representation.

In [10]:
df = meta.to_dataframe()
df.head(3)

,sample_name_original,sample_type,collection_timestamp,country,depth_sample,description,elevation,emp500_principal_investigator,emp500_study_id,emp500_pi_study_id,...,env_feature,env_material,env_package,geo_loc_name,host_subject_id,host_scientific_name,latitude,longitude,project_name,scientific_name
sample_name,,,,,,,,,,,,,,,,,,,,,
13114.angenent.65.s001,Angenent65.misc.104,bioreactor sludge,08/09/2011 0:00,USA - New York,NaN,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65.0,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.104,NaN,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome
13114.angenent.65.s002,Angenent65.misc.519,bioreactor sludge,9/27/12 0:00,USA - New York,NaN,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65.0,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.519,NaN,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome
13114.angenent.65.s003,Angenent65.misc.946,bioreactor sludge,11/28/13 0:00,USA - New York,NaN,Corn Beer Fermentation Bioreactor Biomass,123.0,Angenent,65.0,Angenent65,...,anaerobic bioreactor,anaerobic sludge,host-associated,United States of America:State of New York:Cit...,LTA.misc.104,NaN,42.44,-76.5,Corn Beer Fermentation Bioreactor,bioreactor metagenome

### Metadata Column